$dvi_mode = "0";
$new_viewer_always = "1";
$pdf_mode = "1";
$pdflatex = "xelatex --shell-escape %O %S";
$pdf_previewer = "start zathura %O %S";
$pdf_update_method = "0";
$preview_continuous_mode = "1";
$sleep_time = "3";
$view = "pdf";
